### ISSUE TITLE
Adding frequently used react custom hooks

### ISSUE THREAD

**Issue by shreyaskaundinya** [Mohamed-Ayaan358/code_snips#6]
Adding hooks including but not limited to : 
- useFetch to fetch data [possibly use caching to help with UX]
- useResposiveWindow to use the size of the window for conditional UI 
- useTimeout
- useInterval
- useLocalStorage
- useCopyToClipboard

**Comment by mukunddeepak** [comment]
We shall review your code shortly!

**Comment by Mohamed-Ayaan358** [comment]
@shreyaskaundinya So is your PR only going to comprise of these two files ?

**Comment by shreyaskaundinya** [comment]
Ill write as many as possible in the time that I have...

**Comment by Mohamed-Ayaan358** [comment]
It would be optimal if you can add as many as possible, as PR's are not gonna be accepted for some time. And you  get a higher score
