### ISSUE TITLE
Adding basic codebase for ML model development

### ISSUE THREAD

**Issue by TishaJhabak1014** [Mohamed-Ayaan358/code_snips#6]
This issue will introduce a basic code flow for ML models.

**Comment by TishaJhabak1014** [comment]
@Mohamed-Ayaan358 Created the issue. Kindly assign it to me and add the labels, `hacktobestfest` and `hacktoberfest-accepted`. Thank you.

**Comment by Mohamed-Ayaan358** [comment]
You got to make a pull request I am only putting accepted tag on PR's

**Comment by TishaJhabak1014** [comment]
> You got to make a pull request I am only putting accepted tag on PR's

Okay

**Comment by TishaJhabak1014** [comment]
@Mohamed-Ayaan358 you have merged it. So, I don't have to work on this issue. Right?

**Comment by Mohamed-Ayaan358** [comment]
Nope I have decided that even though it's big it can be used for beginners as a boilerplate code.
