### ISSUE TITLE
A Java method with simple functions

### ISSUE THREAD

**Issue by alfadelta10010** [Mohamed-Ayaan358/code_snips#8]
Sincere apologies for not creating an issue.

I would like to create a Java file with methods for testing if the number is a palindrome, to check if two numbers are divisible, to calculate factorials, to reverse the passed number and to calculate and store the Fibbonacci series until the limit passed as an argument.

I believe such code snippets are very helpful for complex programs, and programmers do not spend time refrencing simple functions.

**Comment by Mohamed-Ayaan358** [comment]
Your PR will be reviewed at the right time
