### ISSUE TITLE
Image to Sketch

### ISSUE THREAD

**Issue by TishaJhabak1014** [Mohamed-Ayaan358/code_snips#8]
This issue will let me add a code snippet for one of the image processing techniques  i.e Image to Sketch using OpenCV. 
Contribution through .ipynb file.

**Comment by TishaJhabak1014** [comment]
@Mohamed-Ayaan358 Issue created. Kindly assign me , add labels.

**Comment by Mohamed-Ayaan358** [comment]
Please do possibly share images along with the code in a folder for ppl to get a hang of how to use the code

**Comment by TishaJhabak1014** [comment]
@Mohamed-Ayaan358 if necessary, do add accepted label here also, and do close the issue.

**Comment by TishaJhabak1014** [comment]
@Mohamed-Ayaan358 Kindly close the issue.
